app.c
CLEAR
user* authUser(user *loginuser)
References red, reset, signIn, signUp.
Referenced by main.
int userMenu()
Referenced by main.
void execUserMenuChoice(int choice, user *loginptr)
References addRecord, CLEAR, deleteRecord, editPassword, editRecord, runCalendar, viewRecord.
Referenced by main.