calendar.c
char* month[][]
Referenced by displayCalendar.
char* week[][]
Referenced by displayCalendar.
int getkey()
Referenced by runCalendar.
void displayCalendar(int, int, int, int[], user *loginptr)
References gotoxy, month, SetColor, week.
Referenced by calendar.
void calendar(int, int, user *loginptr)
References displayCalendar.
Referenced by runCalendar.
void gotoxy(int x, int y)
Referenced by displayCalendar, runCalendar.
void SetColor(int ForgC)
Referenced by displayCalendar.
int runCalendar(user *loginptr)
References calendar, getkey, gotoxy.
Referenced by execUserMenuChoice.