record.c
int mkdir(const char *pathname, mode_t mode)
Referenced by addRecord.
void clean_stdin()
void addRecord(user *loginptr)
References mkdir.
Referenced by execUserMenuChoice.
int deleteRecord(user *loginptr)
Referenced by execUserMenuChoice.
int viewRecord(user *loginptr)
References red, reset.
Referenced by execUserMenuChoice.
int editRecord(user *loginptr)
References red, reset.
Referenced by execUserMenuChoice.