ui_design.c
CLEAR
KNRM
KRED
KGRN
KYEL
KBLU
KCYN
KWHT
void echo(char print[])
void br(int line)
void pre(int tab)
void span(int space)
void ccolor(int clr)
Referenced by loading, welcome_screen.
void welcome_screen()
References ccolor, KBLU, KGRN, KRED, KYEL.
Referenced by main.
void loading()
References ccolor, CLEAR.
Referenced by main.
void middle1(void)
void middtab1(void)
void red()
Referenced by authUser, createuser, editRecord, main, signIn, viewRecord.
void yellow()
void reset()
Referenced by authUser, createuser, editRecord, main, signIn, viewRecord.