user.c
int isuser(const char *username, const char *password, user *loginuser)
Referenced by signIn.
int signIn(user *loginuser)
References isuser, red, reset.
Referenced by authUser.
int availableuser(const char *username)
Referenced by createuser.
void createuser(user *newuser)
References availableuser, red, reset.
Referenced by signUp.
void registeruser(user *newuser)
Referenced by signUp.
int signUp(user *newuser)
References createuser, registeruser.
Referenced by authUser.
int check_password(char *check_pass)
Referenced by editPassword.
int editPassword(user *loginuserptr)
References check_password.
Referenced by execUserMenuChoice.