.TH "app.c" 3 "Tue Jun 23 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app.c \- This is the application file which is used to link everything in the project\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&.\&./include/app\&.h'\fP
.br
\fC#include '\&.\&./include/ui_design\&.h'\fP
.br
\fC#include '\&.\&./include/calendar\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLEAR\fP   system('clear');"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "user * \fBauthUser\fP (user *loginuser)"
.br
.ti -1c
.RI "int \fBuserMenu\fP ()"
.br
.ti -1c
.RI "void \fBexecUserMenuChoice\fP (int choice, user *loginptr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the application file which is used to link everything in the project\&. 


.PP
\fBAuthor\fP
.RS 4
Akhil Dama - akhildama@cmail.carleton.ca 
.PP
Meher Vishnu Kyatham - mehervishnukyatham@cmail.carleton.ca 
.PP
Naveen Billapati- naveenbillapati@cmail.carleton.ca 
.PP
Rajeshwar Reddy Keesara- rajeshwarreddykeesar@cmail.carleton.ca 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEAR   system('clear');"

.SH "Function Documentation"
.PP 
.SS "user* authUser (user * loginuser)"

.SS "void execUserMenuChoice (int choice, user * loginptr)"

.SS "int userMenu ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
