.TH "ui_design.c" 3 "Tue Jun 23 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui_design.c \- In this file we will be handling all the design functionalities of our system\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLEAR\fP   system('clear');"
.br
.ti -1c
.RI "#define \fBKNRM\fP   '\\x1B[0m'"
.br
.ti -1c
.RI "#define \fBKRED\fP   '\\x1B[31m'"
.br
.ti -1c
.RI "#define \fBKGRN\fP   '\\x1B[32m'"
.br
.ti -1c
.RI "#define \fBKYEL\fP   '\\x1B[33m'"
.br
.ti -1c
.RI "#define \fBKBLU\fP   '\\x1B[34m'"
.br
.ti -1c
.RI "#define \fBKCYN\fP   '\\x1B[36m'"
.br
.ti -1c
.RI "#define \fBKWHT\fP   '\\x1B[37m'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBecho\fP (char print[])"
.br
.ti -1c
.RI "void \fBbr\fP (int line)"
.br
.ti -1c
.RI "void \fBpre\fP (int tab)"
.br
.ti -1c
.RI "void \fBspan\fP (int space)"
.br
.ti -1c
.RI "void \fBccolor\fP (int clr)"
.br
.ti -1c
.RI "void \fBwelcome_screen\fP ()"
.br
.ti -1c
.RI "void \fBloading\fP ()"
.br
.ti -1c
.RI "void \fBmiddle1\fP (void)"
.br
.ti -1c
.RI "void \fBmiddtab1\fP (void)"
.br
.ti -1c
.RI "void \fBred\fP ()"
.br
.ti -1c
.RI "void \fByellow\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
In this file we will be handling all the design functionalities of our system\&. 


.PP
\fBAuthor\fP
.RS 4
Akhil Dama - akhildama@cmail.carleton.ca 
.PP
Meher Vishnu Kyatham - mehervishnukyatham@cmail.carleton.ca 
.PP
Naveen Billapati- naveenbillapati@cmail.carleton.ca 
.PP
Rajeshwar Reddy Keesara- rajeshwarreddykeesar@cmail.carleton.ca 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define CLEAR   system('clear');"

.SS "#define KBLU   '\\x1B[34m'"

.SS "#define KCYN   '\\x1B[36m'"

.SS "#define KGRN   '\\x1B[32m'"

.SS "#define KNRM   '\\x1B[0m'"

.SS "#define KRED   '\\x1B[31m'"

.SS "#define KWHT   '\\x1B[37m'"

.SS "#define KYEL   '\\x1B[33m'"

.SH "Function Documentation"
.PP 
.SS "void br (int line)"

.SS "void ccolor (int clr)"

.SS "void echo (char print[])"

.SS "void loading ()"

.SS "void middle1 (void)"

.SS "void middtab1 (void)"

.SS "void pre (int tab)"

.SS "void red ()"

.SS "void reset ()"

.SS "void span (int space)"

.SS "void welcome_screen ()"

.SS "void yellow ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
